sudo: required
services:
  - docker
    
before_install:
  - docker build -t nfayazov/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run nfayazov/react-test npm test -- --coverage

after_success:
  - docker build -t nfayazov/multi-client ./client
  - docker build -t nfayazov/multi-nginx ./nginx
  - docker build -t nfayazov/multi-server ./server
  - docker build -t nfayazov/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  # Push these images to docker hub
  - docker push nfayazov/multi-client
  - docker push nfayazov/multi-nginx
  - docker push nfayazov/multi-server
  - docker push nfayazov/multi-worker
 
 deploy:
  provide: elasticbeanstalk
  region: us-west-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-west-1-722925451625
  bucket_path: docker-multi
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY